### ISSUE TITLE
Expression #14 of SELECT list is not in GROUP BY clause and contains nonaggregated column

### ISSUE THREAD

**Issue by Ekion-1** [ProVisionBG/searchable#1]
I've installed the package and generated the indexes as per the instructions. The indices are visible in `searchable_index` but whenever I try to search I'm getting a `500` error of `1055 Expression #14 of SELECT list is not in GROUP BY clause and contains nonaggregated column`.

The full error is `    "message": "SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #14 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'app.searchable_index.title' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select models.*, (\n                1.5 * (MATCH (searchable_index.title) AGAINST (BTT )) +\n                1 * (MATCH (searchable_index.title, searchable_index.content) AGAINST (BTT ))\n                ) as searchableScore from `models` left join `searchable_index` on `searchable_index`.`searchable_id` = `models`.`id` and `searchable_index`.`searchable_type` = App\\Model where MATCH(searchable_index.title, searchable_index.content) AGAINST(BTT ) group by `models`.`id` order by `searchableScore` desc)",
`

**Comment by veneliniliev** [comment]
can you try disable `only_full_group_by` in MySQL?

**Comment by Ekion-1** [comment]
This works locally but my database is managed by DigitalOcean so don't have the ability to change this in production.

**Comment by Ekion-1** [comment]
Apologies, it appears as though I **can** change this. Trying now...

**Comment by veneliniliev** [comment]
in `config/database.php`
you can change
```
 'connections' => [
        'mysql' => [
...
            'strict' => false,
...
 
        ]
    ]
```

or

```
  'connections' => [
        'mysql' => [
            // Ignore this key and rely on the strict key
            'modes' => null,

            // Explicitly disable all modes, overriding strict setting
            'modes' => [],

            // Explicitly enable specific modes, overriding strict setting
            'modes' => [
                'STRICT_TRANS_TABLES',
                'ONLY_FULL_GROUP_BY',
            ],
        ]
    ]
```

**Comment by AlexGodbehere** [comment]
Ok, ignoring production for a moment. I've ran `SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));` to disable the setting locally, which I can verify with `SHOW VARIABLES;` however I'm still getting the same `500` message when running the search.

**Comment by Ekion-1** [comment]
> in `config/database.php`
> you can change
> 
> ```
>  'connections' => [
>         'mysql' => [
> ...
>             'strict' => false,
> ...
>  
>         ]
>     ]
> ```
> 
> or
> 
> ```
>   'connections' => [
>         'mysql' => [
>             // Ignore this key and rely on the strict key
>             'modes' => null,
> 
>             // Explicitly disable all modes, overriding strict setting
>             'modes' => [],
> 
>             // Explicitly enable specific modes, overriding strict setting
>             'modes' => [
>                 'STRICT_TRANS_TABLES',
>                 'ONLY_FULL_GROUP_BY',
>             ],
>         ]
>     ]
> ```

Setting `strict = false` solved the issue, thanks.

**Comment by nezaboravi** [comment]
This not helped me

**Comment by nezaboravi** [comment]
```
Syntax error or access violation: 1055 Expression #120 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'agri.searchable_index.title' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select count(*) as aggregate from (select ads.*, (
                1.5 * (MATCH (searchable_index.title) AGAINST (some deere )) +
                1 * (MATCH (searchable_index.title, searchable_index.content) AGAINST (some deere ))
                ) as searchableScore from `ads` left join `searchable_index` on `searchable_index`.`searchable_id` = `ads`.`id` and `searchable_index`.`searchable_type` = App\Ad where MATCH(searchable_index.title, searchable_index.content) AGAINST(some deere ) group by `ads`.`id`) as `aggregate_table`)
```
