### ISSUE TITLE
Is there a way to partly search words?

### ISSUE THREAD

**Issue by Ekion-1** [ProVisionBG/searchable#2]
Assume I have a search index containing `15 Leafbrook Crescent`. By default I have to search for `Leafbrook` before the result shows up. Is there a way to return the result when I search for `Leaf` only?

**Comment by veneliniliev** [comment]
yes, you can.
your search query must be "leaf*"

you can see more boolean search operators on: https://dev.mysql.com/doc/refman/8.0/en/fulltext-boolean.html
