### ISSUE TITLE
Not returning results as should have

### ISSUE THREAD

**Issue by nezaboravi** [ProVisionBG/searchable#4]
When I type "cultivator" return 0 result. Type "cultivators", returns 23

If I type "tractor", nothing returns. Type tractors, it returns a result.
So, part of the word is not recognized, therefore kind of useless.

![image](https://user-images.githubusercontent.com/1515172/108372812-7ba5e180-71ff-11eb-808f-301e13572e1e.png)

![image](https://user-images.githubusercontent.com/1515172/108372983-ae4fda00-71ff-11eb-8a69-d1467b4e8cec.png)

**Comment by hlorofos** [comment]
;-D Awesome issue

**Comment by veneliniliev** [comment]
hi, read this docs: https://dev.mysql.com/doc/refman/8.0/en/fulltext-boolean.html

_"*
The asterisk serves as the truncation (or wildcard) operator. Unlike the other operators, it is appended to the word to be affected. Words match if they begin with the word preceding the * operator.
"_

try search with "**cultivator***"

_"'apple*'
Find rows that contain words such as “apple”, “apples”, “applesauce”, or “applet”."_
