### ISSUE TITLE
Undefined object: 7 ERROR:  type "fulltext_title" does not exist

### ISSUE THREAD

**Issue by IlhamShiddiq** [ProVisionBG/searchable#7]
Hello,

Is anyone has a problem like me, while i run command `php artisan migrate`, this error will appear.

`SQLSTATE[42704]: Undefined object: 7 ERROR:  type "fulltext_title" does not exist at character 43 (SQL: ALTER TABLE searchable_index ADD FULLTEXT fulltext_title(title))`

Please help,
Thankyou

**Comment by veneliniliev** [comment]
What database are you using?

**Comment by IlhamShiddiq** [comment]
> What database are you using?

I am using PostgreSQL, I think the query on the migration file only works with MySQL right?

Any solution for Postgre?

**Comment by veneliniliev** [comment]
The library only works with MySQL. If you can make a solution for PostgreSQL you can post a PR.
